config/routes.rb
Rails.application.routes.draw do

	resources :articles do
		resources :comments
	end

	resources :comments do
    	resources :comments
  	end

  	resources :categories do
    	resources :categories
  	end

  	resources :photos do
  		resources :comments
  	end
  	

  	post 'load_fullsize_image/:id',  :to => 'photos#load_fullsize_image'

	resources :buildings do
		resources :comments
		resources :categories
		resources :photos do 

			collection do
				
				match 'load_photos_menu', 		 :to => 'photos#load_photos_menu',   :via => [:post]
				match 'load_slider_photos',  	 :to => 'photos#load_slider_photos', :via => [:post]
				match 'new/load_slider_photos',  :to => 'photos#load_slider_photos', :via => [:post]	
			end

		end

		resources :schemas do

			patch "photo_marker_update/:id", 	:to => 'photo_markers#update'
			post  "photo_marker_create", 		:to => 'photo_markers#create'
			post  "photo_marker_destroy/:id", 	:to => 'photo_markers#destroy'

			patch "guide_marker_update/:id", 	:to => 'guide_markers#update'
			post  "guide_marker_create", 		:to => 'guide_markers#create'
			post  "guide_marker_destroy/:id", 	:to => 'guide_markers#destroy'

			post  'show_guide_marker',		:to => 'guide_markers#show'
			post  'show_photo_marker',		:to => 'photo_markers#show'

			post  'upload_photo',		 	:to => 'schemas#upload_photo'

			post 'check_can_edit',			:to => 'schemas#check_can_edit'

			
			match "load_photo_markers" => 'photo_markers#index',  :via => [:post]

			match "load_guide_markers" => 'guide_markers#index',  :via => [:post]

			match "load_guides" => 'guides#index',  :via => [:post]

			match 'load_placed_photos',  :to => 'schemas#load_placed_photos', :via => [:post]

			match 'load_unplaced_photos',  :to => 'schemas#load_unplaced_photos', :via => [:post]	

			match 'new_guide', :to => 'guides#new', :via => [:post]	

			match 'edit_guide/:id', :to => 'guides#edit', :via => [:post]	

		end

		post 'buildings/:id/photos', :to => 'photos#create'
 
		match 'photos/load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]	

		match 'load_schema_photos', :to => 'photos#load_thumbnail_slider', :via => [:post]

	end


	resources :schemas, :only => :index do
  		resources :guides
	end

	resources :guides, :only => :index do
		resources :comments
	end



	post "load_thumbnail_image/:id", :to => "photos#load_thumbnail_image"
	

	get "/add_like/:id", :to => "likes#addLike", as: 'add_like', constraints: { id: /[0-9]{0,5}/}

  	get "/comment_reply" => 'comments#comment_reply', as: 'comment_reply'
  	get "/comment_edit" => 'comments#comment_edit', as: 'comment_edit'

  	resources :users do
  		resources :photos, :controller => "user_photos" do
  			collection do
  				match 'load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]
  				match 'load_slider_photos', :to => 'photos#load_slider_photos', :via => [:post] 
  			end
  		end

  		resources :comments, :controller => "user_comments"

  		
  	end

	get "user/setting", :to => "users#setting"


	get "/photo_editor" => 'photos#photo_editor', as: 'photo_editor'
	
	resources :news
	
	root 'news#index'

	get "news/create", :to => "news#create"
	
	get "session/signup", :to => "users#new"
	get "session/login", :to => "sessions#login"
	get "session/logout", :to => "sessions#logout"
	get "home", :to => "sessions#home"

	get 'get_current_user_id' => "users#get_current_user_id"

	patch "user/update", :to => "users#update"

	# routes for static pages
	get "/pages/:page" => "pages#show"

	namespace :admin do

		resources :articles, :comments, :users, :news, :buildings

		resources :categories do
    		resources :categories
  		end


		get '', to: 'dashboard#index', as: '/'

		get "add_subcategory" => "categories#add_subcategory"
		patch "categories" => "categories#update", :as => "admin/categories/update"
		patch "user/update" => "users#update", :as => "admin/users"


		get "dashboard/publish_comment" => "dashboard#publish_comment", :as => "admin/publish_comment"
		get "articles/publish/:id"   => "articles#publish"
		get "buildings/publish/:id"  => "buildings#publish"
		
	end	

	post ':controller(/:action(/:id))(.:format)'
	
end

app/models/schema.rb
class Schema < ActiveRecord::Base

	belongs_to :user
	belongs_to :building, counter_cache: true
	
	has_many   :photo_markers, :dependent => :destroy
	has_many   :guide_markers, :dependent => :destroy

	has_many   :photos, through: :photo_markers
	has_many   :guides, through: :guide_markers

	validates :title, :presence => true

	mount_uploader :schema, SchemaUploader

end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController

	before_filter :authenticate_user, :only => [:new, :create, :destroy, :edit, :upload_photo]
	before_filter :parent_object, :except => [ :load_schema_photos, :photo_position_update, :destroy ]

	load_and_authorize_resource :only => [:create, :destroy, :edit, :update]

	layout "building"

	def index
		@schemas = @building.schemas

		if @schemas.length == 0
			render :partial => "schemas/partials/no_schemas"
			return
		end

		if params[:layout] == 'false'
			render :layout => false 
		end
	end

	def create

		new_params = schema_params
		new_params[:user_id] = current_user.id

		@schema = @building.schemas.new(new_params)

		if @schema.save
			redirect_to building_schema_path( @building, @schema )
		else
			flash[:error] = @schema.errors.full_messages
			render 'new'
		end

	end

	def show

		@schema = @building.schemas.find(params[:id])

		render :layout => "schema"

	end

	def edit

		render :layout => "building"

	end

	def update

		new_params = Hash.new

		new_params[:title]		  = params[:schema][:title]
		new_params[:text]  		  = params[:schema][:text]

		if !params[:schema][:building_id].blank?
			new_params[:building_id]  = params[:schema][:building_id]
		end

		if params.key?('building_id') && !params[:building_id].blank?
			new_params[:building_id]  = params[:building_id]
		end

		if !params[:schema][:schema].blank?

		 	new_params[:schema] = params[:schema][:schema]

		end

		if @schema.update( new_params )
			flash[:success] = "запись обновлена"
			redirect_to building_schema_path( @building, @schema )
		else
			flash[:error] 	= "произошла ошибка"
			redirect_to edit_building_schema_path( @building, @schema )
		end

	end

	def upload_photo

		ids = Array.new

		if !params.has_key?(:post_photos)
			return
		end

		params[:post_photos].each do |a|

			new_params = { user_id: current_user.id , image: a, building_id: params[:building_id] }

			@photo = @building.photos.new( new_params )

			@photo.save!

			ids.push @photo.id

		end

		@photos = Photo.where( id: ids )
		
		render :json => @photos

	end


	def load_placed_photos 
		photos = Schema.find(params[:schema_id]).photos
		render :json => photos
	end

	def load_unplaced_photos 
		photos = @building.photos.where("schema_id is NULL")
		render :json => photos
	end

	def check_can_edit

		if can_manage?(@building)
			response = true
		else
			response = false
		end

		render :json => response

	end


	protected


		def schema_params
			params.require(:schema).permit( :title, :user_id, :text, :building_id, :schema )
		end

		def parent_object

			@building = Building.select([ :id, :title, :category_id, :image, :status, :photos_count, :schemas_count, :user_id ]).find(params[:building_id])
			@category = category_select('Building').find_all { |category| category.id == @building.category_id}[0]
			
		end

end

app/views/schemas/partials/_add_photo_button.html.erb
<%= form_for [ @building, Photo.new  ], html: { id: 'schema-add-photo-container' } do |f| %>
	
	<div id="schema-add-photo-button" class="schema-add-photo-button"></div>
	<input id="add-schema-photo-input" class="add-schema-photo-input" type="file" name="post_photos[]"/> 

	
<% end %>

app/views/schemas/partials/_no_schemas.html.erb
<div id="content-inner-wrap" class="inner-wrap post-wrapper">
	<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: name %>
	<% end -%>
	    
	<div class="dark-background-input-area">    
	    <p class="light-gray-text">к сожалению схема для данного сооружения отсутствует</p><br>
	    <%= link_to 'добавить новую схему', new_building_schema_path( @building ), :class => 'add-photo-gray-button' %>
	</div>
</div>

app/views/schemas/partials/_schema_preview.html.erb
<li class="schema-preview-content shadow">

	<span class="creation-date"><%= schema.created_at.strftime("%d %B %Y") %></span>
	<%=  link_to building_schema_path( @building, schema ), class: 'header-link', data: { no_turbolink: true }, :rel => 'nofollow' do %>
		<h3><%= schema.title %></h3>
	<% end %>
	
	<p><%= schema.text %></p>
   
</li>    

app/views/schemas/partials/_sidebar.html.erb
<div id="main-sidebar">
	<div class="page-title">
		<div id="sidebar-menu-toggle" class="sidebar-menu-toggle"></div>
		<div id="sidebar-title">
			<%= link_to 'все схемы сооружения', building_schemas_path(@building) %>
		</div>
	</div>
	<div id="sidebar-content">
		<div id="schema-menu-section">
			<div id="schema-menu-titles">
				<div id="schema-photos-title" class="active">
					<span>
						фотографии
					</span>
				</div>
				<div id="schema-guides-title">
					<span>
						экспликация
					</span>
				</div>
			</div>
			<div id="schema-menu-main-conteiner">
				<div id="schema-photos-conteiner">
				</div>
				<div id="schema-guides-container">
				</div>
			</div>	
		</div>

		</div>
	</div>

</div>

app/views/schemas/partials/_sidebar_menu.html.erb
<ul>
    <%- @schemas.each do |schema| %>
        <li>
            <%= link_to schema.title, building_schema_path( building_id, schema.id ), :class => 'remote-link' %>
        </li>
    <% end %>
    <%- if can? :create, Schema %>
	    <li>
	        <%= link_to 'добавить...', new_building_schema_path %>
	    </li>
    <% end %>
    
</ul>