config/routes.rb
Rails.application.routes.draw do

	resources :articles do
		resources :comments
	end

	resources :comments do
    	resources :comments
  	end

  	resources :categories do
    	resources :categories
  	end

  	resources :photos do
  		resources :comments
  	end
  	

  	post 'load_fullsize_image/:id',  :to => 'photos#load_fullsize_image'

	resources :buildings do
		resources :comments
		resources :categories
		resources :photos do 

			collection do
				
				match 'load_photos_menu', 		 :to => 'photos#load_photos_menu',   :via => [:post]
				match 'load_slider_photos',  	 :to => 'photos#load_slider_photos', :via => [:post]
				match 'new/load_slider_photos',  :to => 'photos#load_slider_photos', :via => [:post]	
			end

		end

		resources :schemas do

			patch "photo_marker_update/:id", 	:to => 'photo_markers#update'
			post  "photo_marker_create", 		:to => 'photo_markers#create'
			post  "photo_marker_destroy/:id", 	:to => 'photo_markers#destroy'

			patch "guide_marker_update/:id", 	:to => 'guide_markers#update'
			post  "guide_marker_create", 		:to => 'guide_markers#create'
			post  "guide_marker_destroy/:id", 	:to => 'guide_markers#destroy'

			post  'show_guide_marker',		:to => 'guide_markers#show'
			post  'show_photo_marker',		:to => 'photo_markers#show'

			post  'upload_photo',		 	:to => 'schemas#upload_photo'

			post 'check_can_edit',			:to => 'schemas#check_can_edit'

			
			match "load_photo_markers" => 'photo_markers#index',  :via => [:post]

			match "load_guide_markers" => 'guide_markers#index',  :via => [:post]

			match "load_guides" => 'guides#index',  :via => [:post]

			match 'load_placed_photos',  :to => 'schemas#load_placed_photos', :via => [:post]

			match 'load_unplaced_photos',  :to => 'schemas#load_unplaced_photos', :via => [:post]	

			match 'new_guide', :to => 'guides#new', :via => [:post]	

			match 'edit_guide/:id', :to => 'guides#edit', :via => [:post]	

		end

		post 'buildings/:id/photos', :to => 'photos#create'
 
		match 'photos/load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]	

		match 'load_schema_photos', :to => 'photos#load_thumbnail_slider', :via => [:post]

	end


	resources :schemas, :only => :index do
  		resources :guides
	end

	resources :guides, :only => :index do
		resources :comments
	end



	post "load_thumbnail_image/:id", :to => "photos#load_thumbnail_image"
	

	get "/add_like/:id", :to => "likes#addLike", as: 'add_like', constraints: { id: /[0-9]{0,5}/}

  	get "/comment_reply" => 'comments#comment_reply', as: 'comment_reply'
  	get "/comment_edit" => 'comments#comment_edit', as: 'comment_edit'

  	resources :users do
  		resources :photos, :controller => "user_photos" do
  			collection do
  				match 'load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]
  				match 'load_slider_photos', :to => 'photos#load_slider_photos', :via => [:post] 
  			end
  		end

  		resources :comments, :controller => "user_comments"

  		
  	end

	get "user/setting", :to => "users#setting"


	get "/photo_editor" => 'photos#photo_editor', as: 'photo_editor'
	
	resources :news
	
	root 'news#index'

	get "news/create", :to => "news#create"
	
	get "session/signup", :to => "users#new"
	get "session/login", :to => "sessions#login"
	get "session/logout", :to => "sessions#logout"
	get "home", :to => "sessions#home"

	get 'get_current_user_id' => "users#get_current_user_id"

	patch "user/update", :to => "users#update"

	# routes for static pages
	get "/pages/:page" => "pages#show"

	namespace :admin do

		resources :articles, :comments, :users, :news, :buildings

		resources :categories do
    		resources :categories
  		end


		get '', to: 'dashboard#index', as: '/'

		get "add_subcategory" => "categories#add_subcategory"
		patch "categories" => "categories#update", :as => "admin/categories/update"
		patch "user/update" => "users#update", :as => "admin/users"


		get "dashboard/publish_comment" => "dashboard#publish_comment", :as => "admin/publish_comment"
		get "articles/publish/:id"   => "articles#publish"
		get "buildings/publish/:id"  => "buildings#publish"
		
	end	

	post ':controller(/:action(/:id))(.:format)'
	
end

app/models/article.rb
class Article < ActiveRecord::Base

	mount_uploader :image, ThumbUploader

	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h 

 	after_update :generate_thumbnails

	IMAGE_SIZES = {
    	:thumb => [300, 300]
 	}

 	RU_NAME = 'статьи' 

	belongs_to :category
  belongs_to :user, counter_cache: true
	has_many :comments, as: :commentable, dependent: :destroy
  	has_many :likes, as: :likeable, dependent: :destroy

	validates :title, presence: true,
                    length: { minimum: 5 }
             

  self.per_page = 10

  def generate_thumbnails
      image.recreate_versions! if image.present? && self.crop_x.present?
  end
  
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

	before_filter :authenticate_user, :is_admin?

  layout 'admin'
    
  def is_admin?
    if not current_user.is? :admin
        redirect_to root_path
    end 
  end

  def index
  	@articles = Article.where(:published => false)
  end

  def show
  	@article = Article.find(params[:id])
  end

  def update
		@article = Article.find(params[:id])
 
		if @article.update(article_params)
			redirect_to action: 'index'
		else
			render 'edit'
		end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to action: 'index'
  end

  def publish
    @article = Article.find(params[:id])
    @article.published = true
    @article.save
    redirect_to action: 'index' 
  end

  private
		def article_params
			params.require(:article).permit(:title, :text)
		end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	layout "article"

	before_filter :authenticate_user, :only => [:new, :create, :destroy, :edit]
	before_filter :is_admin?, :only => [:destroy]

	load_and_authorize_resource :only => [:create, :destroy, :edit, :update]

	def index

		@categories = Category.all
		
		if params[:category_id]		

			ids = get_children_categories_ids(params[:category_id])

			@articles = Article.select(index_params)
								.where( :category_id => ids )
								.paginate(:page => params[:page])

		else

			@articles = Article.select(index_params)
								.where(:published => true )
								.order(id: :desc)
								.paginate(:page => params[:page])

		end

			render :layout => false if params[:layout] == 'false'

	end

	def show
		@article = Article.find(params[:id])
		@categories = category_select('Article')
		@owner = User.select([:id, :username]).find( @article.user_id )
	end
	
	def new
		@article = Article.new
		@categories = category_select('Article')
	end
	
	def edit
		@categories = category_select('Article')
	end
	
	def create

		new_params = article_params
		new_params[:user_id] = current_user.id

		if current_user.role != 'member' && current_user.role != 'guest'
			new_params[:published] = true
		end

		@article = Article.new(new_params)
 
		if @article.save
			flash[:success] = "запись успешно добавлена"
			redirect_to @article
		else
			render 'new'
		end
	end
	
	def update

		@categories = Category.where( parent: 1)

		if @article.update(article_params)
			flash[:success] = "запись обновлена"
			redirect_to @article
		else
			flash[:error] = "запись не обновлена"
			render 'edit'
		end
	end
	
	
	private

		def index_params
			index_params = [:id, :title, :intro, :image, :created_at, :era, :category_id, :user_id]
		end

		def article_params
			params.require(:article).permit(:title, :crop_x, :crop_y, :crop_w, :crop_h, :text, :category_id, :image, :user_id, :intro, :era )
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div id="article-form">
  <%= form_for @article, :html => { :class => 'form-wrapper' } do |f| %>
   
    <%= render partial: 'shared/errors', object: @article, :as => 'post' %>

    <%= f.label :title, "заголовок статьи", :class => 'form-label' %>
    <%= f.text_field :title, class: 'form-input' %>


    <%= f.label :intro, "введение", :class => 'form-label' %>
    <p class="help-text">этот текст выводится в качестве аннотации к статье и должен вкратце описывать содержимое статьи</p>
    <%= f.text_field :intro, class: 'form-input' %>

   
    <%= f.label :text, "основное содержание", :class => 'form-label' %>
    <p class="help-text">пока мы не сделали графического текстового редактора HTML теги нужно добавлять вручную</p>
    <%= f.text_area :text, class: 'form-input form-text' %>


    <div class="field">
      <%= f.label :image, "изображение", :class => 'form-label' %>
      <p class="help-text">изображение является обложкой данной статьи.<br>Старайтесь, чтобы превью изоражения имело размер не менее 300 пикселей</p>
    


    <% if f.object.image.present? %>
        <%= image_tag f.object.image.thumb.url, id: "old-image-preview" %>
    <% end %>  

    <div id="post-image-upload">
        <div id="image-editor-area">
        </div>
        <div id="image_upload-area">  
          <%= f.file_field :image, id: 'image-input-field', :data => { :edit => true, 
                                         :default_size => '300x300',
                                         :keep_aspect => true
                                        } %>
        </div>
    </div>


    <div> 
      <div class="form-label">категория</div>
      <label class="select-label">
        <%= select_tag "article[category_id]", options_from_collection_for_select(@categories, "id", "title", :selected=>@article.category_id )%>
      </label>
    </div>

    <div>
      <div class="form-label">эпоха</div>
      <label class="select-label">
            <%= select_tag "article[era]", options_for_select([ "1900", "1910", "1920", "1930", "1940", "1950", "1960", "1970", "1980", "1990" ], @article.era ) %>
      </label>
      <br>
    </div>
    
    <br>

    <div class="confirm-green-button">
      <%= f.submit "опубликовать статью" %>
    </div>

      <%= link_to 'к списку статей', articles_path, class: "abort-operation-button" %>
   
  <% end %>
</div>

app/views/articles/_index_sidebar.html.erb
<div id="main-sidebar">
	<div class="page-title">
		<div id="sidebar-menu-toggle" class="sidebar-menu-toggle"></div>
		<div id="sidebar-title">
			<%= link_to Article::RU_NAME, :action => :index %>
		</div>
	</div>
	<div id="sidebar-content">
		<nav id="sidebar-main-navigation">
			<%= build_category_tree %>
		</nav>

		<%= link_to 'добавить статью', new_article_path, :rel => 'nofollow', class: "add-post-button"  if can? :create, Article %>
	</div>
</div>

app/views/articles/edit.html.erb
<div id="content-inner-wrap" class="inner-wrap">	

	<h2>редактирование статьи "<%= @article.title %>"</h2>	 
	<%= render 'form' %>
		 
</div>

app/views/articles/index.html.erb
<div id="content-inner-wrap" class="inner-wrap"> 

  <ul class="articles-list">
      
     <%= render(:partial => 'shared/post_preview', :collection => @articles, :as => 'post') || 'В разделе пока нет ни одной записи' %>

  </ul>

  <%= will_paginate @articles %>

</div>

app/views/articles/new.html.erb
<div id="content-inner-wrap" class="inner-wrap">	
	<h2>новая статья</h2>
	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="content-inner-wrap" class="inner-wrap">	

	<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: name %>
	<% end -%>

	<%= render partial: 'shared/post_content', object: @article, as: 'post', :locals => {:owner => @owner }  %>

	<p class="call-to-comment">
	hiddenhistory является открытым проектом, и поэтому если вы можете дополнить эту статью или обнаружили какие-то ошибки или неточности вы можете сообщить об этом в комментариях. Мы будем благодарны за любую помощь!
	</p>

	<div id="comment-section">

		<% if @article.comments.count > 0 %>
			<div class="strong-header">комментарии к статье:</div>

			<div id="comment-list">
				<%= render @article.comments.select { |c| c[:published] == true }  %>
			</div>	

		<% end -%>

	</div>

	
				
				
	<br><br>
	<div class="strong-header">добавить комментарий:</div>
	
	<%= render partial: 'comments/form', object: @article, as: 'commentable' %>

</div>

<script type="text/javascript">
    $(document).on('turbolinks:load', function() {
        $(window).trigger('article-show-start')
    });
</script>