config/routes.rb
Rails.application.routes.draw do

	resources :articles do
		resources :comments
	end

	resources :comments do
    	resources :comments
  	end

  	resources :categories do
    	resources :categories
  	end

  	resources :photos do
  		resources :comments
  	end
  	

  	post 'load_fullsize_image/:id',  :to => 'photos#load_fullsize_image'

	resources :buildings do
		resources :comments
		resources :categories
		resources :photos do 

			collection do
				
				match 'load_photos_menu', 		 :to => 'photos#load_photos_menu',   :via => [:post]
				match 'load_slider_photos',  	 :to => 'photos#load_slider_photos', :via => [:post]
				match 'new/load_slider_photos',  :to => 'photos#load_slider_photos', :via => [:post]	
			end

		end

		resources :schemas do

			patch "photo_marker_update/:id", 	:to => 'photo_markers#update'
			post  "photo_marker_create", 		:to => 'photo_markers#create'
			post  "photo_marker_destroy/:id", 	:to => 'photo_markers#destroy'

			patch "guide_marker_update/:id", 	:to => 'guide_markers#update'
			post  "guide_marker_create", 		:to => 'guide_markers#create'
			post  "guide_marker_destroy/:id", 	:to => 'guide_markers#destroy'

			post  'show_guide_marker',		:to => 'guide_markers#show'
			post  'show_photo_marker',		:to => 'photo_markers#show'

			post  'upload_photo',		 	:to => 'schemas#upload_photo'

			post 'check_can_edit',			:to => 'schemas#check_can_edit'

			
			match "load_photo_markers" => 'photo_markers#index',  :via => [:post]

			match "load_guide_markers" => 'guide_markers#index',  :via => [:post]

			match "load_guides" => 'guides#index',  :via => [:post]

			match 'load_placed_photos',  :to => 'schemas#load_placed_photos', :via => [:post]

			match 'load_unplaced_photos',  :to => 'schemas#load_unplaced_photos', :via => [:post]	

			match 'new_guide', :to => 'guides#new', :via => [:post]	

			match 'edit_guide/:id', :to => 'guides#edit', :via => [:post]	

		end

		post 'buildings/:id/photos', :to => 'photos#create'
 
		match 'photos/load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]	

		match 'load_schema_photos', :to => 'photos#load_thumbnail_slider', :via => [:post]

	end


	resources :schemas, :only => :index do
  		resources :guides
	end

	resources :guides, :only => :index do
		resources :comments
	end



	post "load_thumbnail_image/:id", :to => "photos#load_thumbnail_image"
	

	get "/add_like/:id", :to => "likes#addLike", as: 'add_like', constraints: { id: /[0-9]{0,5}/}

  	get "/comment_reply" => 'comments#comment_reply', as: 'comment_reply'
  	get "/comment_edit" => 'comments#comment_edit', as: 'comment_edit'

  	resources :users do
  		resources :photos, :controller => "user_photos" do
  			collection do
  				match 'load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]
  				match 'load_slider_photos', :to => 'photos#load_slider_photos', :via => [:post] 
  			end
  		end

  		resources :comments, :controller => "user_comments"

  		
  	end

	get "user/setting", :to => "users#setting"


	get "/photo_editor" => 'photos#photo_editor', as: 'photo_editor'
	
	resources :news
	
	root 'news#index'

	get "news/create", :to => "news#create"
	
	get "session/signup", :to => "users#new"
	get "session/login", :to => "sessions#login"
	get "session/logout", :to => "sessions#logout"
	get "home", :to => "sessions#home"

	get 'get_current_user_id' => "users#get_current_user_id"

	patch "user/update", :to => "users#update"

	# routes for static pages
	get "/pages/:page" => "pages#show"

	namespace :admin do

		resources :articles, :comments, :users, :news, :buildings

		resources :categories do
    		resources :categories
  		end


		get '', to: 'dashboard#index', as: '/'

		get "add_subcategory" => "categories#add_subcategory"
		patch "categories" => "categories#update", :as => "admin/categories/update"
		patch "user/update" => "users#update", :as => "admin/users"


		get "dashboard/publish_comment" => "dashboard#publish_comment", :as => "admin/publish_comment"
		get "articles/publish/:id"   => "articles#publish"
		get "buildings/publish/:id"  => "buildings#publish"
		
	end	

	post ':controller(/:action(/:id))(.:format)'
	
end

app/views/shared/_admin_sidebar.html.erb
<div id="admin-sidebar">
	<nav>
		<%= link_to 'панель управления', :controller => :dashboard, :action => :index %>
		<%= link_to 'новости', {:controller => :news, :action => :index } %>		
		<%= link_to 'статьи', 	:controller => :articles, :action => :index %>
		<%= link_to 'сооружения', :controller => :buildings, :action => :index %>
		<%= link_to 'категории объектов', {:controller => :categories, :action => :index, :parent_resourse => 'Building'} %>
		<%= link_to 'категории статей', {:controller => :categories, :action => :index, :parent_resourse => 'Article'} %>
		<%= link_to 'пользователи', {:controller => :users, :action => :index } %>		
	</nav>
</div>

app/views/shared/_errors.html.erb
<% if post.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(post.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login_menu.html.erb
<div id="top-login-menu">
	<div id="login-section">
		<% if signed_in? -%>
			<div><%= link_to 'личный кабинет', user_path( current_user.id ) %></div>
			<div>
				<%= 
				if current_user.image.icon.url
						image_tag current_user.image.icon.url, class: "login-menu-icon-img" 
					else
						image_tag("default-user-icon.png")
					end
				%>	
			</div>
			<div><%= link_to 'выход', controller: '/session', action: 'logout' %></div>
		<% else -%>
			<div><%= link_to 'вход', controller: '/session', action: 'login' %></div>
			<div><%= link_to 'регистрация', :controller => :pages, :action => :show, :page => 'registration' %></div>
		<% end -%>
	</div>
	<%= image_tag '/assets/hh-logo.png', :width => 16, :height => 25, :class => 'header-hh-logo' %>
	<%= link_to 'HIDDENHISTORY', { controller: '/news', action: 'index' }, id: "header-home-link" %>
</div>

app/views/shared/_moderation.html.erb
<div class="notification-box">
  В настоящее время запись проходит модерацию и пока невидима для других польхователей. <br> Для просмотра и редактирования вы можете найти эту запись в личном кабинете
</div>

app/views/shared/_news_sidebar.html.erb
<div id="main-sidebar">
	<div id="page-title" class="page-title">
		<div id="sidebar-menu-toggle" class="sidebar-menu-toggle"></div>
		<div id="sidebar-title">
			<%= link_to 'История XX века', { controller: '/news', action: 'index' } %>
		</div>
	</div>
	<div id="sidebar-content">
		<ul id="news-sidebar-era-select">
			<li>
				<div>
					<%= link_to '1900', :controller => :news, :action => :index, :era => '1900' %>
				</div>		
			</li>
			<li>
				<div>
					<%= link_to '1910', :controller => :news, :action => :index, :era => '1910' %>
				</div>	
			</li>
			<li>
				<div>
					<%= link_to '1920', :controller => :news, :action => :index, :era => '1920' %>
				</div>
			</li>
			<li>
				<div>
					<%= link_to '1930', :controller => :news, :action => :index, :era => '1930' %>
				</div>
			</li>
			<li>
				<div>
					<%= link_to '1940', :controller => :news, :action => :index, :era => '1940' %>
				</div>	
			</li>
			<li>
				<div>
					<%= link_to '1950', :controller => :news, :action => :index, :era => '1950' %>
				</div>
			</li>
			<li>
				<div>
					<%= link_to '1960', :controller => :news, :action => :index, :era => '1960' %>
				</div>
			</li>
			<li>
				<div>
					<%= link_to '1970', :controller => :news, :action => :index, :era => '1970' %>
				</div>	
			</li>
			<li>
				<div>
					<%= link_to '1980', :controller => :news, :action => :index, :era => '1980' %>
				</div>	
			</li>
			<li>
				<div>	
					<%= link_to '1990', :controller => :news, :action => :index, :era => '1990' %>
				</div>	
			</li>
		</ul>
	</div>
</div>

app/views/shared/_object_category.html.erb
<ul class="post-category">
	<li><%= post.era %></li>
	<li><%= link_to post.class::RU_NAME, 
			:controller => ( post.class.to_s.downcase + 's' ),
			:action => :index
			%>
	</li>

	<li><%= link_to title=@categories.find_all { |category| category.id == post.category_id}[0]["title"],
			:controller => ( post.class.to_s.downcase + 's' ), 
			:action => :index, 
			:category_id => post.category_id
			%>
	</li>	
</ul>

app/views/shared/_post_content.html.erb
<article id="article-main">

	<header class="article-header">
		<h1><%= post.title %></h1>
		<ul>
			<li><%= owner.username %></li> | 
			<li><%= post.created_at.strftime("%d %B %Y") %></li>
		</ul>
	</header>

	<div class="article-body white-box shadow">

		<% if post.published == false %>
			<%= render(:partial => 'shared/moderation' ) %>
		<% end %>
					
		<%= kramdown post.text %>

		<% if can? :edit, post %>
     		 <div class="admin-edit-links">
        		<%= link_to 'редактировать', edit_polymorphic_path(post), data: { no_turbolink: true }  %>
     	 	</div>
    	<% end %>

	</div>

</article>

app/views/shared/_post_preview.html.erb
<li class="post-preview-content shadow">
  	
  	<% if post.image.thumb.present? %>
		<%=  link_to polymorphic_path(post), data: { no_turbolink: true } do %>
		        <%= image_tag post.image.thumb.url %>
		<% end %>
	<% end %>
	
  	<div class="post-preview-main">
	    <div class="post-preview-body">

	      <span class="creation-date"><%= post.created_at.strftime("%d %B %Y") %></span>
	      <%=  link_to polymorphic_path(post), class: 'header-link', data: { no_turbolink: true } do %>
	        <%= post.title %>
	      <% end %>
	    
	      <p><%= post.intro %></p>
	                    
	    </div>

	    <div class="post-preview-footer">
    		<%= render partial: 'shared/object_category', object: post, :as => 'post' if post.has_attribute?('category_id') %> 
    	</div>

    </div> 
               
</li>    

app/views/shared/_profile_sidebar.html.erb
<div id="main-sidebar" class="user-profile-sidebar">
	<div id="page-title" class="page-title">
		<div id="sidebar-menu-toggle" class="sidebar-menu-toggle"></div>
		<div id="sidebar-title">
			профиль пользователя
		</div>
	</div>
	<div id="sidebar-content">
		<%= if @user.image.thumb.url
				image_tag @user.image.thumb.url, class: "user-profile-big-img" 
		end %>
		<nav id="sidebar-main-navigation">
			<ul class="sidebar-nav-level-0">
				<li>
					<%= link_to 'комментарии', user_comments_path( @user.id ) %>
				</li>
				<li id="sidebar-photo-content">
					<%= link_to 'фотографии',  user_photos_path( @user.id ), :class => 'remote-link', 
																				 :data => { background: '#2b2b2b' } %>
				</li>
			</ul>
		</nav>
	</div>
</div>

app/views/shared/_top_menu.html.erb
<div id="top-navigation-menu">
	<div class="top-nav-inner-wrap">
		<nav>
			<ul>
				<li><%= link_to 'сооружения', controller: 'buildings'%></li>
				<li><%= link_to 'статьи', controller: 'articles' %></li>
				<li><%= link_to 'о проекте', :controller => :pages, :action => :show, :page => 'about' %></li>
			</ul>
		</nav>
	</div>
</div>