config/routes.rb
Rails.application.routes.draw do

	resources :articles do
		resources :comments
	end

	resources :comments do
    	resources :comments
  	end

  	resources :categories do
    	resources :categories
  	end

  	resources :photos do
  		resources :comments
  	end
  	

  	post 'load_fullsize_image/:id',  :to => 'photos#load_fullsize_image'

	resources :buildings do
		resources :comments
		resources :categories
		resources :photos do 

			collection do
				
				match 'load_photos_menu', 		 :to => 'photos#load_photos_menu',   :via => [:post]
				match 'load_slider_photos',  	 :to => 'photos#load_slider_photos', :via => [:post]
				match 'new/load_slider_photos',  :to => 'photos#load_slider_photos', :via => [:post]	
			end

		end

		resources :schemas do

			patch "photo_marker_update/:id", 	:to => 'photo_markers#update'
			post  "photo_marker_create", 		:to => 'photo_markers#create'
			post  "photo_marker_destroy/:id", 	:to => 'photo_markers#destroy'

			patch "guide_marker_update/:id", 	:to => 'guide_markers#update'
			post  "guide_marker_create", 		:to => 'guide_markers#create'
			post  "guide_marker_destroy/:id", 	:to => 'guide_markers#destroy'

			post  'show_guide_marker',		:to => 'guide_markers#show'
			post  'show_photo_marker',		:to => 'photo_markers#show'

			post  'upload_photo',		 	:to => 'schemas#upload_photo'

			post 'check_can_edit',			:to => 'schemas#check_can_edit'

			
			match "load_photo_markers" => 'photo_markers#index',  :via => [:post]

			match "load_guide_markers" => 'guide_markers#index',  :via => [:post]

			match "load_guides" => 'guides#index',  :via => [:post]

			match 'load_placed_photos',  :to => 'schemas#load_placed_photos', :via => [:post]

			match 'load_unplaced_photos',  :to => 'schemas#load_unplaced_photos', :via => [:post]	

			match 'new_guide', :to => 'guides#new', :via => [:post]	

			match 'edit_guide/:id', :to => 'guides#edit', :via => [:post]	

		end

		post 'buildings/:id/photos', :to => 'photos#create'
 
		match 'photos/load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]	

		match 'load_schema_photos', :to => 'photos#load_thumbnail_slider', :via => [:post]

	end


	resources :schemas, :only => :index do
  		resources :guides
	end

	resources :guides, :only => :index do
		resources :comments
	end



	post "load_thumbnail_image/:id", :to => "photos#load_thumbnail_image"
	

	get "/add_like/:id", :to => "likes#addLike", as: 'add_like', constraints: { id: /[0-9]{0,5}/}

  	get "/comment_reply" => 'comments#comment_reply', as: 'comment_reply'
  	get "/comment_edit" => 'comments#comment_edit', as: 'comment_edit'

  	resources :users do
  		resources :photos, :controller => "user_photos" do
  			collection do
  				match 'load_photos_menu', :to => 'photos#load_photos_menu',    :via => [:post]
  				match 'load_slider_photos', :to => 'photos#load_slider_photos', :via => [:post] 
  			end
  		end

  		resources :comments, :controller => "user_comments"

  		
  	end

	get "user/setting", :to => "users#setting"


	get "/photo_editor" => 'photos#photo_editor', as: 'photo_editor'
	
	resources :news
	
	root 'news#index'

	get "news/create", :to => "news#create"
	
	get "session/signup", :to => "users#new"
	get "session/login", :to => "sessions#login"
	get "session/logout", :to => "sessions#logout"
	get "home", :to => "sessions#home"

	get 'get_current_user_id' => "users#get_current_user_id"

	patch "user/update", :to => "users#update"

	# routes for static pages
	get "/pages/:page" => "pages#show"

	namespace :admin do

		resources :articles, :comments, :users, :news, :buildings

		resources :categories do
    		resources :categories
  		end


		get '', to: 'dashboard#index', as: '/'

		get "add_subcategory" => "categories#add_subcategory"
		patch "categories" => "categories#update", :as => "admin/categories/update"
		patch "user/update" => "users#update", :as => "admin/users"


		get "dashboard/publish_comment" => "dashboard#publish_comment", :as => "admin/publish_comment"
		get "articles/publish/:id"   => "articles#publish"
		get "buildings/publish/:id"  => "buildings#publish"
		
	end	

	post ':controller(/:action(/:id))(.:format)'
	
end

app/models/building.rb
class Building < ActiveRecord::Base

	belongs_to :category
	belongs_to :user, counter_cache: true

	has_many   :comments, as: :commentable, dependent: :destroy
	has_many   :photos,  dependent: :destroy
	has_many   :schemas, dependent: :destroy
	has_many   :buildings

	mount_uploader :image, ThumbUploader

	validates :title, :presence => true, :length => { :in => 3..100 }

	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h 

 	after_update :generate_thumbnails

	IMAGE_SIZES = {
    	:thumb => [300,  300]
 	}

 	STATUSES = {
 		'ru' => [ 'используется', 'заброшен', 'уничтожен','приспособлен','музей' ]
 	}

	RU_NAME = 'здания и сооружения'


	self.per_page = 10

	def generate_thumbnails
   		image.recreate_versions! if image.present? && self.crop_x.present?
  	end
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < ApplicationController

	before_filter :authenticate_user, :is_admin?

  layout 'admin'
    
  def is_admin?
    if not current_user.is? :admin
        redirect_to root_path
    end 
  end

  def index
  	@buildings= Building.where(:published => false)
  end

  def show
    @building = Building.find(params[:id])
  end

  def update
		@building = Building.find(params[:id])
 
		if @building.update(building_params)
			redirect_to action: 'index'
		else
			render 'edit'
		end
  end

  def publish
    @building = Building.find(params[:id])
    @building.published = true
    @building.save
    redirect_to action: 'index' 
  end

  def destroy
    @building = Building.find(params[:id])
    @building.destroy
 
    redirect_to action: 'index'
  end

  private
		def building_params
			params.require(:building).permit(:title, :text)
		end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

	layout "building_index"

	before_filter :authenticate_user, :only => [:new, :create, :destroy, :edit, :update]
	before_filter :is_admin?, :only => [:destroy]

	load_and_authorize_resource :only => [:create, :destroy, :edit, :update]

	def index
		
		@categories = Category.all

		if params[:category_id]

			ids = get_children_categories_ids(params[:category_id])

			@buildings = Building.select(index_params)
									.where( :category_id => ids )
									.where( 'building_id is NULL' )
									.where(:published => true )
									.order(id: :desc)
									.paginate(:page => params[:page])
			
			if params[:layout] == 'false' && !params.key?('page')
				render :layout => false 
			end

		else
			@buildings = Building.select(index_params)
								.where( 'building_id is NULL' )
								.where(:published => true )
								.order(id: :desc)
								.paginate(:page => params[:page])
		end

	end

	def show

		@building = Building.includes('buildings').find(params[:id])

		if @building.building_id != nil 

			@parent = Building.select([:id, :title]).find( @building.building_id )

		end

		@category = category_select('Building').find_all { |category| category.id == @building.category_id}[0]

		@owner = User.select([:id, :username]).find( @building.user_id )

		render :layout => 'building'
	end

	def new

		if params.has_key?(:id) 
			@parent_building = Building.find(params[:id])
			@building = @parent_building.buildings.new
		else 
			@building = Building.new
		end

		@categories = category_select('Building')

	end

	def create

		new_params = building_params

		if current_user.role != 'member' && current_user.role != 'guest'
			new_params[:published] = true
		end

		@building = current_user.buildings.new(new_params)
 
		if @building.save

			flash[:success] = 'изменения успешно сохранены'

			redirect_to @building
		else
			flash[:error] = @building.errors.full_messages

			@categories = Category.all

			render action: 'new'
		end
	end

	def edit

		@categories = category_select('Building')

	end

	def update
		
		if @building.update(building_params)
			flash[:success] = "запись обновлена"
			redirect_to @building
		else
			flash[:error] = "запись не обновлена"
			render 'edit'
		end
	end

	private

		def index_params
			index_params = [:id, :title, :intro, :image, :created_at, :era, :category_id, :user_id]
		end

		def building_params
			params.require(:building).permit(:title, :crop_x, :crop_y, :crop_w, :crop_h, :intro, :text, :category_id, :building_id, :image, :latitude, :longitude, :status, :user_id, :era )
		end
end

app/helpers/buildings_helper.rb
module BuildingsHelper

	def build_basic_info
		html = '<div id="building-basic-info">'
		html += '<p>текущий статус: <span>' << Building::STATUSES['ru'][@building.status] << '</span></p>'
		html += '<p>тип сооружения: <span>' << @category.title << '</span></p>'
		html += '</div>'

		return html.html_safe
	end
end

app/views/buildings/_form.html.erb
<div id="building-form">
  <%= form_for @building, :html => { :class => 'form-wrapper' } do |f| %>
   
    <%= render partial: 'shared/errors', object: @building, :as => 'post' %>


    <%= f.label :title, "название здания/сооружения", :class => 'form-label' %>
    <%= f.text_field :title, class: 'form-input' %>


    <%= f.label :intro, "краткое описание", :class => 'form-label' %>
    <p class="help-text">этот текст выводится в качестве аннотации к статье и должен вкратце описывать содержимое статьи</p>
    <%= f.text_field :intro, class: 'form-input' %>

     <%= f.label  :building_id, "id родительского сооружения", :class => 'form-label' %>
    <p class="help-text">если сооружение находится на территории или является частью другого сооружения, вы здесь следует указать id этого сооружения. </p>
    <%= f.text_field :building_id, class: 'form-input' %>

   
    <%= f.label :text, "полное описание", :class => 'form-label' %>
    <p class="help-text">пока мы не сделали графического текстового редактора HTML теги нужно добавлять вручную</p>
    <%= f.text_area :text, class: 'form-input form-text' %>


    <div class="field">
      <%= f.label :image, "изображение", :class => 'form-label' %>
      <p class="help-text">изображение является обложкой данной статьи.<br>Старайтесь, чтобы превью изоражения имело размер не менее 300 пикселей</p>

    <% if f.object.image.present? %>
        <%= image_tag f.object.image.thumb.url, id: "old-image-preview" %>
    <% end %>  

    <div id="post-image-upload">
        <div id="image-editor-area">
        </div>
        <div id="image_upload-area">
            <%= f.file_field :image, id: 'image-input-field', :data => { :edit => true, 
                                           :default_size => '300x300',
                                           :keep_aspect => true
                                          } %>
        </div>
    </div>
    
   

    <div class="form-label"> категория<br>
      <label class="select-label">
        <%= select_tag "building[category_id]", options_from_collection_for_select(@categories, "id", "title", :selected=>@building.category_id)%>
      </label>
    </div>

    <div class="form-label">эпоха<br>
      <label class="select-label">
            <%= select_tag "building[era]", options_for_select([ "1900", "1910", "1920", "1930", "1940", "1950", "1960", "1970", "1980", "1990" ], @building.era ) %>
      </label>
      <br>
    </div>

    <div class="form-label">статус<br>
      <label class="select-label">
            <%= select_tag "building[status]", options_for_select( Building::STATUSES['ru'].each_with_index.map {|name, index| [name,index]} , :selected=>@building.status ) %>
      </label>
      <br>
    </div>

    <br>

    <div class="confirm-green-button">
      <%= f.submit "опубликовать статью" %>
    </div>

      <%= link_to 'к списку статей', articles_path, class: "abort-operation-button" %>
   
  <% end %>


</div>

app/views/buildings/_index_sidebar.html.erb
<div id="main-sidebar">
	<div class="page-title">
		<div id="sidebar-menu-toggle" class="sidebar-menu-toggle"></div>
		<div id="sidebar-title">
			<%= link_to Building::RU_NAME, :action => :index %>
		</div>
	</div>
	<div id="sidebar-content">
		<nav id="sidebar-main-navigation">
			<%= build_category_tree %>
		</nav>
		<%= link_to 'добавить сооружение', new_building_path, :rel => 'nofollow', class: "add-post-button"  if can? :create, Building %>
	</div>
</div>

app/views/buildings/_nested_building.html.erb
<li class="post-preview-content-small">
  <%= image_tag post.image.thumb.url, class: "rounded-preview-img" if post.image.thumb.present? %>
    <div class="post-preview-body">

      <%=  link_to post.title , building_path(post), class: 'header-link', data: { no_turbolink: true } %>

      <p><%= post.intro %></p>

      <%= post.era %>
                    
    </div>  
                
</li>    

app/views/buildings/_show_sidebar.html.erb
<div id="main-sidebar">
	<div class="page-title">
		<div id="sidebar-menu-toggle" class="sidebar-menu-toggle"></div>
		<div id="sidebar-title">
			<%= link_to 'сооружения', buildings_path %>
		</div>
	</div>
	<div id="sidebar-content">
		<% if @building.image.url != nil %>
			<%= build_basic_info %>
			<%= image_tag @building.image.thumb.url, id: 'sidebar-post-image', class: "building-sidebar-image" if @building.image != nil %>
		<% end %>
		<div id="building-content-navigation">
			<div id="sidebar-main-navigation">
				<ul class="sidebar-nav-level-0">

					<li id="sidebar-article-content">
						<div class="sidebar-icon icon-info"></div>
						<%= link_to 'описание', building_path(@building), data: { no_turbolink: true } %>
					</li>
					<li id="sidebar-photo-content">
					<span class="sidebar-items-count"><%= @building.photos_count %></span>
					<div class="sidebar-icon icon-photo"></div>
					<%= link_to "фотографии", building_photos_path(@building ), :class => 'remote-link'  %>
																				
					</li>
					<span class="sidebar-items-count"><%= @building.schemas_count %></span>
					<li id="sidebar-schema-content">
					<div class="sidebar-icon icon-schemas"></div>
					<%= link_to "схемы", building_schemas_path(@building), :class => 'remote-link'   %>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
</div>

app/views/buildings/edit.html.erb
<div class="white-article-background">

	<div id="content-inner-wrap" class="inner-wrap">	

		<h2>редактировать сооружение</h2>

			<div class="form-label">добавить дочернее сооружение</div><br>
  			<%= link_to 'добавить сооружение', new_building_path( :id => @building.id ) , class: "add-post-button"  %>

		<%= render 'form' %>
		
	</div>

</div>

<script type="text/javascript">
	$(window).trigger('image-uploader-start')
</script>

app/views/buildings/index.html.erb
<div id="content-inner-wrap" class="inner-wrap"> 


    <ul class="articles-list">
      
      <%= render(:partial => 'shared/post_preview', :collection => @buildings, :as => 'post') || 'В разделе пока нет ни одной записи' %>

    </ul>
    
    <hr>
    
    <%= will_paginate @buildings %>

   
  </div>

app/views/buildings/new.html.erb
<div class="white-article-background">

	<div class="inner-wrap">
		<h2>новое сооружение</h2>
		<%= render 'form' %>
	</div>

</div>

<script type="text/javascript">
	$(window).trigger('image-uploader-start')
</script>

app/views/buildings/show.html.erb
<div id="content-inner-wrap" class="inner-wrap">	
		<% flash.each do |name, msg| -%>
			<%= content_tag :div, msg, class: name %>
		<% end -%>

		<%= render partial: 'shared/post_content', object: @building, as: 'post', :locals => {:owner => @owner }  %>


		<% if  @building.buildings.count > 0 %>
			<div class="nested-buildings-section white-box shadow">
				<span class="nb-header">дочерние сооружения</span>

				<ul class="nested-buildings-list">
					<%= render(:partial => 'nested_building', :collection => @building.buildings , :as => 'post') %>
				</ul>
			</div>
		<% end %>


		<p class="call-to-comment">
		hiddenhistory является открытым проектом, и поэтому если вы можете дополнить эту статью или обнаружили какие-то ошибки или неточности вы можете сообщить об этом в комментариях. Мы будем благодарны за любую помощь!
		</p>

		<div id="comment-section">

			<% if @building.comments.count > 0 %>
				<div class="strong-header">комментарии к статье:</div>

				<ul id="comment-list" class="white-box shadow">
					<%= render @building.comments.select { |c| c[:published] == true }  %>
				</ul>
			<% end -%>

		</div>
	
		<br><br>

		<div class="strong-header">добавить комментарий:</div>

		<%= render partial: 'comments/form', object: @building, as: 'commentable' %>
		
</div>

<script type="text/javascript">
    $(document).on('turbolinks:load', function() {
        $(window).trigger('article-show-start')
    });
</script>